<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\Facepunch.Console.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\Facepunch.Network.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\servers\Rust_Devblog_65\server\RustDedicated_Data\Managed\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
